### ISSUE TITLE
Marker List Usability changes

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/350GroupProject#11]
When  you press the accordion to open the information about a pin, if the name is near the bottom the of view it open out of view, is there a way to automatically scroll the box so the marker information is always in visible?

**Comment by PhlexPlexico** [comment]
Working on this. Still need help with accordion class.

**Comment by PhlexPlexico** [comment]
Updates: Got it to work, but it's extremely wonky and could use some looking over.

**Comment by magnusandy** [comment]
dont bother, tis fine
