### ISSUE TITLE
Sharing button

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/350GroupProject#19]
there is a few options here, either we have the generic share button we have now, but this should share based on what service you are logged into (google plus or facebook)
or we can have a single standard facebook/g+ button dependong on what they are logged in with or I think the best idea is to have both buttons on the bar of the page both styled to be easily recongnizable as google or facebook share buttons (maybe get the standard ones from those providers).

Also we should maybe think about the share button on the shareDisplay page, should we:
- removed it
- or have it share the currently shared page i.e. not your page, the page your viewing

**Comment by PhlexPlexico** [comment]
Definitely the page you're currently being shared. Will try and fix that tomorrow.

**Comment by magnusandy** [comment]
The share button should be styled like facebook blue or something to make it clear its sharing on facebook

**Comment by magnusandy** [comment]
now they just need to be updated on the sharedisplay page
