### ISSUE TITLE
floating "create pin on me"

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/350GroupProject#21]
When you only have a few pins in your marker list, < 5, the "create pin on me" button kinda floats in the middle of the page (because it is below the marker holder box, is there a way we can either move it to a less awkward place or have the marker box shrink when you only have a few markers

**Comment by PhlexPlexico** [comment]
This would require having that button load dynamically as well. I think it'd be best to place it on top of the markers page, rather than below all of it since it would be above that div.
