### ISSUE TITLE
TODO: display page

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/350GroupProject#4]
This page should be very similar in design to the display page of assignment 2, it should get the information for each pin from the database and display them on the map. The tricky part about this will be getting the information from php and creating n number of markers(with javascript). My suggestion would be to use and AJAX call to a seperate php page, and echo back the marker information as a JSON object. see http://www.dyn-web.com/tutorials/php-js/json/array.php for more details. this link http://stackoverflow.com/questions/23740548/how-to-pass-variables-and-data-from-php-to-javascript also gives a good summary of what we will need to do (See 1. Use AJAX to get the data you need from the server)

**Comment by magnusandy** [comment]
https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple
might be the simplest way to display info on the markers, it also leaves it open to easily adding an image or something later on. 
as well, we can easily customize the pin color, image etc, without effecting the data or without much futzing

**Comment by magnusandy** [comment]
see the description of [this](https://github.com/magnusandy/350GroupProject/commit/2e0d150da8f4da618f2fabd3b67109b35471685e) commit for some more information about how we might need to go about this page

**Comment by magnusandy** [comment]
might also  be able to use jquery to build the page

**Comment by PhlexPlexico** [comment]
Hurr we done?

**Comment by magnusandy** [comment]
is Update done?
