### ISSUE TITLE
Form popup for adding pins

### ISSUE THREAD

**Issue by PhlexPlexico** [magnusandy/350GroupProject#8]
I have the submit button currently:

onclick="return hideForm();"

hideform is a function on scripts.js that hides the form (obviously). I also have a function setup in maps.js called submitPin() that will make the pin. The issue is, if I cann hideForm() without the return, it refreshes the page, but anytime I try and call submitPin() it refreshes the page. This is an issue because I need to call both submitPin() and hideForm() in no particular order, but I can't double return call (just doesnt work, tried it).

So the php idea we had was find a way to save the form's info then refresh the page. We wouldn't need to call hideForm() since the form starts hidden anyways, so just need to save the data through the refresh, if that makes sense.

**Comment by magnusandy** [comment]
not sure what this is so i am closing it
